"""empty message

Revision ID: 9cfb81e6f9f9
Revises: 6155b74d2a60
Create Date: 2018-12-10 10:58:36.434883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfb81e6f9f9'
down_revision = '6155b74d2a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('re_address', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('re_address', 'is_delete')
    # ### end Alembic commands ###
