"""empty message

Revision ID: 3d4dc3971a94
Revises: 
Create Date: 2018-12-11 14:49:03.990777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4dc3971a94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('commentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_content', sa.Text(), nullable=True),
    sa.Column('c_parentid', sa.Integer(), nullable=True),
    sa.Column('co_user', sa.String(length=64), nullable=True),
    sa.Column('strategy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['co_user'], ['user.u_name'], ),
    sa.ForeignKeyConstraint(['strategy'], ['strategy.s_id'], ),
    sa.PrimaryKeyConstraint('commentid')
    )
    op.create_table('collect',
    sa.Column('collectid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_good', sa.Boolean(), nullable=True),
    sa.Column('c_user', sa.Integer(), nullable=True),
    sa.Column('c_goods', sa.Integer(), nullable=True),
    sa.Column('c_strategy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['c_goods'], ['goods.g_id'], ),
    sa.ForeignKeyConstraint(['c_strategy'], ['strategy.s_id'], ),
    sa.ForeignKeyConstraint(['c_user'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('collectid')
    )
    op.create_table('evaluate',
    sa.Column('e_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('e_content', sa.Text(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('e_parentid', sa.Integer(), nullable=True),
    sa.Column('ev_user', sa.String(length=64), nullable=True),
    sa.Column('ev_goods', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ev_goods'], ['goods.g_id'], ),
    sa.ForeignKeyConstraint(['ev_user'], ['user.u_name'], ),
    sa.PrimaryKeyConstraint('e_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluate')
    op.drop_table('collect')
    op.drop_table('comment')
    # ### end Alembic commands ###
