"""empty message

Revision ID: 5f36aff12089
Revises: 
Create Date: 2018-12-11 22:07:57.133211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f36aff12089'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('com_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_time', sa.DateTime(), nullable=True),
    sa.Column('c_content', sa.Text(), nullable=True),
    sa.Column('co_user', sa.Integer(), nullable=True),
    sa.Column('c_strategy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['c_strategy'], ['strategy.s_id'], ),
    sa.ForeignKeyConstraint(['co_user'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('com_id')
    )
    op.create_table('recomment',
    sa.Column('nt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nt_content', sa.Text(), nullable=True),
    sa.Column('nt_parentid', sa.Integer(), nullable=True),
    sa.Column('nt_time', sa.DateTime(), nullable=True),
    sa.Column('nt_bname', sa.String(length=64), nullable=True),
    sa.Column('nt_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nt_user'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('nt_id')
    )
    op.create_table('reevaluate',
    sa.Column('te_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('te_content', sa.Text(), nullable=True),
    sa.Column('te_parentid', sa.Integer(), nullable=True),
    sa.Column('te_time', sa.DateTime(), nullable=True),
    sa.Column('te_bname', sa.String(length=64), nullable=True),
    sa.Column('te_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['te_user'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('te_id')
    )
    op.create_table('evaluate',
    sa.Column('e_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('e_content', sa.Text(), nullable=True),
    sa.Column('e_time', sa.DateTime(), nullable=True),
    sa.Column('ev_user', sa.Integer(), nullable=True),
    sa.Column('ev_goods', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ev_goods'], ['goods.g_id'], ),
    sa.ForeignKeyConstraint(['ev_user'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('e_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluate')
    op.drop_table('reevaluate')
    op.drop_table('recomment')
    op.drop_table('comment')
    # ### end Alembic commands ###
