"""empty message

Revision ID: 7dc5c7963e4e
Revises: 5f36aff12089
Create Date: 2018-12-12 09:16:51.672404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc5c7963e4e'
down_revision = '5f36aff12089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paygoods', sa.Column('pgoodsnum', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paygoods', 'pgoodsnum')
    # ### end Alembic commands ###
