"""empty message

Revision ID: b7166eaba029
Revises: 
Create Date: 2018-12-12 10:01:59.905233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7166eaba029'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deal_ibfk_1', 'deal', type_='foreignkey')
    op.drop_column('deal', 'd_pay')
    op.add_column('paygoods', sa.Column('pa_deal', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paygoods', 'deal', ['pa_deal'], ['d_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paygoods', type_='foreignkey')
    op.drop_column('paygoods', 'pa_deal')
    op.add_column('deal', sa.Column('d_pay', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('deal_ibfk_1', 'deal', 'paygoods', ['d_pay'], ['paygoodsid'])
    # ### end Alembic commands ###
