"""empty message

Revision ID: e6437697cc22
Revises: 3d4dc3971a94
Create Date: 2018-12-11 16:24:04.809192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6437697cc22'
down_revision = '3d4dc3971a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal',
    sa.Column('d_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('d_user', sa.Integer(), nullable=True),
    sa.Column('d_pay', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['d_pay'], ['paygoods.paygoodsid'], ),
    sa.ForeignKeyConstraint(['d_user'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('d_id')
    )
    op.add_column('comment', sa.Column('c_time', sa.DateTime(), nullable=True))
    op.add_column('evaluate', sa.Column('e_time', sa.DateTime(), nullable=True))
    op.add_column('strategy', sa.Column('s_collectnum', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy', 's_collectnum')
    op.drop_column('evaluate', 'e_time')
    op.drop_column('comment', 'c_time')
    op.drop_table('deal')
    # ### end Alembic commands ###
